#!/bin/bash
#: Title           : addff.sh
#: Date            : 2018-06-19
#: Author          : "Kamil Piekutowski" <influence1982@gmail.com>
#: Version         : 1.0
#: Description     : Adds values provided from file that contains a column of data
#: Options         : None

awk '{s+=$1}END{print s}' $1
